### PR TITLE
Tranformer for Multiple

### PR DESCRIPTION
**Pull request by veelenga**
The deprecation itself: http://ember-cli-page-object.js.org/docs/v1.17.x/deprecations#multiple

We have a fat ember app coupled to ember-cli-page-object, where the occurrence of `multiple: true` is too high to update it by hand. I decided to make the transformer in order to speed up the refactoring.

I used a getter as an alternative to `multiple: true` for all of the page object attributes because:

1. it allows having a single pattern for all the places to update
2. it doesn't imply changing the end test

**Before:**

```js
tags: text('.tag', { multiple: true })
```

**After:**
```js
_tags: collection('.tag'),

tags: {
  isDescriptor: true,

  get: function() {
    return this._tags.map((el) => el.text);
  }
}
```

*See the [rendered README.md](https://github.com/ro0gr/ember-page-object-codemod/blob/cc8e7bba6af73b479c7e84ddcd48b072d99b01c4/transforms/multiple/README.md) for details and more examples.*

### CODE REVIEW

**Review by ro0gr — COMMENTED** [review]
This looks amazing! 

I'll do my best to pay enough attention to the PR this weekend. Meanwhile, just got few questions when briefly reviewed:

1. What happens if the private property name is already used? Let's say the codemod intends to create an intermediate `_tags` collection, but the `_tags` is already used for some purpose. Would it fail or would it create duplicated `_tags` property declaration. I'm fine with either solution, just want to make sure we've considered the edge case.

2. Can we have a test case making sure it works with a plain definition(w/o `create(`) please? Like:

```ts
import { property } from 'ember-cli-page-object';

export default {
  scope: 'div',
  disabled: property('disabled', '.tags', { multiple: true })
};  
```

3. Have you considered using of `getter` from the `ember-cli-page-object/extend` in order to reduce amount of the generated boilerplate? Smth like:

Before:
```ts
tags: text('.tag', { multiple: true })
```

After:
```ts
_tags: collection('.tag'),

tags: getter(function() {
  return this._tags.map((el) => el.text);
}
```
The only blocker for that I can imagine could be if we intended to support the actions + `multiple`, but as far as [I can see](https://github.com/ro0gr/ember-page-object-codemod/blob/cc8e7bba6af73b479c7e84ddcd48b072d99b01c4/transforms/multiple/README.md#multiple-clickable) we don't intend to do it, and I think this is correct.

**Comment by veelenga** [comment]
@ro0gr thanks for the feedback.

1. In the beginning I planned not to transform such property at all (ignore it), but then I realized that for the developer it is just easier to do some small post refactoring. So, it creates a duplicate property and the developer will have to fix that manually. But this is a really rare case through  

2. Good catch, will do. **UPD:** https://github.com/ro0gr/ember-page-object-codemod/pull/17/commits/832e8d5db9d49a3a1532c97c518dc4c6f953934e

3. That was just easier to use a regular getter property to avoid extra work for importing `getter` from `ember-cli-page-object/extend`. But can do this as well if you think this is required.

**Comment by ro0gr** [comment]
Hey @veelenga, unfortunately I haven't managed to finish my review just yet, due to some of my family activities this weekend. However, I've started working on it.

First, thanks for your update to respect a POJO use case! I've also checked the codemod against TS codebase, and it seems to work fine.

While testing I've found some cases when the codemod fails to work:

 - Seems like it does assume that page object definition should be a default export only, so cases like
```ts
const NestedPage = { // this object is not recognized as a page object
  test: attribute('src', '', {
    multiple: true
  })
};

export default {
  nested2: NestedPage
};
```

would fail to convert some cases for composition of few definitions defined in a single file, or page objects which are created in place in a test module for example.

- nested page objects seem to be ignored, like:
```ts
export default {
  nested: {
    test: attribute('src', '', { // seems like this is ignored at the moment, because it's not a top level object prop
      multiple: true
    })
  },
};
```
would stay unmodified.

----

>  but then I realized that for the developer it is just easier to do some small post refactoring. So, it creates a duplicate property and the developer will have to fix that manually. But this is a really rare case through

I agree, this seems to be the simlest(best) approach to go with.


> That was just easier to use a regular getter property to avoid extra work for importing getter from ember-cli-page-object/extend. But can do this as well if you think this is required.

from aestethics point of view, I think one may want to have a `getter(` as the end result of the codemod since it's less verbose. However, though I tend to prefer `getter(` in general, both `getter` and your approach do exactly the same, so I think this is not a big deal for me.

**Comment by veelenga** [comment]
> would fail to convert some cases for composition of few definitions defined in a single file, or page objects which are created in place in a test module for example.

This was [done by intention](https://github.com/ro0gr/ember-page-object-codemod/blob/832e8d5db9d49a3a1532c97c518dc4c6f953934e/transforms/multiple/index.js#L211-L217) to limit the possible false positiveness in other cases.

**Comment by ro0gr** [comment]
@veelenga not sure what you mean under the false positives. I believe, conceptually there is nothing wrong with having multiple definitions per file, even if some of them are not exported. Can you say more what kind of errors we are trying to avoid here please?

**Comment by veelenga** [comment]
@ro0gr I meant, that I white-listed the possible scenarios I'm aware of. This would guarantee that some other cases (when the transformation may be unintended) are not covered. 

However, when I revisited this, seems like the chance to get such false positives is quite small. Because I already whitelisted the callees which have the `multiple` property:

```js
const SUPPORTED_TEXT_BASED_PROPS = ['text', 'value'];
const SUPPORTED_BOOL_BASED_PROPS = ['isVisible', 'isHidden', 'isPresent'];
const SUPPORTED_SCOPE_BASED_PROPS = ['attribute', 'property', 'hasClass', 'notHasClass'];
const SUPPORTED_PROP_CALLEE_NAMES = [
  ...SUPPORTED_TEXT_BASED_PROPS,
  ...SUPPORTED_BOOL_BASED_PROPS,
  ...SUPPORTED_SCOPE_BASED_PROPS,
];

```

**Pull request closed without merging**
